name: Update Blog Posts

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install feedparser gitpython

      - name: Run script to update blog
        run: python .github/scripts/update_blog.py
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
